id = "xy-zed-sauronato"
name = "XY-Zed Theme Forked By Sauronato"
version = "0.1.1"
schema_version = 1
authors = ["Daniel Zarifpour <z@rifpour.xyz>", "David AlcalÃ¡"]
description = "ğŸˆâ€â¬› A sleek and sophisticated dark theme with vibrant, intelligent syntax highlighting. Please report issues â©"
repository = "https://github.com/Sauronato/xy-zed"
